// Auto-generated by tools/generate_directory_content.py from HA_To_Make_Tier2_Tier3.xlsx.
// DO NOT EDIT MANUALLY — amend the workbook and regenerate.
window.HA_TO_MAKE_CONTENT = {
  "generatedFrom": "HA_To_Make_Tier2_Tier3.xlsx",
  "images": {
    "logo": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/1f3bfb43-558e-4262-b2e2-d4e3b56bd77e/01-the-hope-anthology.jpg?content-type=image%2Fjpeg",
    "star": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/470da432-cdf9-45be-b3ba-2e9599ce5f4f/04-the-hope-anthology-botanical-star.png?content-type=image%2Fpng"
  },
  "navigation": [
    {
      "label": "To Keep",
      "url": "/to-keep"
    },
    {
      "label": "To Make",
      "url": "/to-make"
    },
    {
      "label": "The Story",
      "url": "/story"
    },
    {
      "label": "Collaborate",
      "url": "/collaborate"
    },
    {
      "label": "Collective",
      "url": "/collective"
    }
  ],
  "page": {
    "eyebrow": "To Make",
    "headingHtml": "Curated <em>Makers</em>",
    "intro": "A growing anthology of people who design things for other people to make. Patterns, templates and guides — chosen because making is one of the oldest ways there is of getting through something.",
    "stats": [
      {
        "value": 2,
        "label": "FOUNDING MAKERS"
      },
      {
        "value": 80,
        "label": "PATTERNS"
      },
      {
        "value": 1,
        "label": "MEDIUM SO FAR"
      }
    ]
  },
  "filters": {
    "medium": [
      "All mediums",
      "Stained glass"
    ],
    "level": [
      "All levels",
      "Beginner",
      "Improver"
    ],
    "delivery": [
      "All delivery",
      "Instant download",
      "Posted to you"
    ]
  },
  "recruitment": {
    "eyebrow": "FOUNDING MAKERS",
    "heading": "Do you design things for other people to make?",
    "body": "Patterns, templates, guides — any medium. Free for the founding year, no commission ever. I just need some images, a bit of a description about you, and some links.",
    "linkLabel": "See how it works for artists →",
    "linkUrl": "/collaborate"
  },
  "collective": {
    "heading": "Something worth being part of.",
    "body": "New designs, behind-the-scenes making, and the occasional reminder that you’re doing better than you think. No noise. No pressure. Just the Anthology.",
    "buttonLabel": "Join the Collective",
    "buttonUrl": "/collective"
  },
  "footer": {
    "privacyUrl": "/privacy-policy",
    "accessibilityUrl": "/accessibility",
    "copyright": "© The Hope Anthology 2026"
  },
  "makers": [
    {
      "slug": "nell-hardy-e3",
      "active": true,
      "name": "Nell Hardy E3",
      "buttonName": "Nell",
      "artistNumber": 3,
      "badge": "Founding maker",
      "heroImage": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/e7e1635a-4c43-41e7-bb27-5df1b7eaba60/Nell-Hardy-artist-profile.jpg?content-type=image%2Fjpeg",
      "heroAlt": "Pattern guide behind a moon stained glass pattern that has been made.",
      "medium": "Stained glass patterns",
      "filterMedium": "Stained glass",
      "collections": [
        "Bundles",
        "Celestial",
        "Geometric & abstract"
      ],
      "priceFrom": "£3.50",
      "difficulty": "Beginner",
      "technique": "Copper foil",
      "delivery": "Instant download",
      "feeling": "Celestial and geometric patterns for a first cut into glass.",
      "traits": [
        "Beginner-friendly",
        "Celestial & geometric",
        "Printable PDF"
      ],
      "cardUrl": "/to-make/nell-hardy-e3",
      "patternCount": 33
    },
    {
      "slug": "ellien-bruce-e4",
      "active": true,
      "name": "Ellien Bruce E4",
      "buttonName": "Ellien",
      "artistNumber": 4,
      "badge": "Founding maker",
      "heroImage": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/1b720069-ca67-4110-934d-a9325a2073f1/Eillen-Bruce-artist-profile.jpg?content-type=image%2Fjpeg",
      "heroAlt": "Stained glass butterfly that has been made from one of the patterns.",
      "medium": "Stained glass patterns",
      "filterMedium": "Stained glass",
      "collections": [
        "Animals & birds",
        "Bundles",
        "Insects & bugs",
        "Nature & flowers"
      ],
      "priceFrom": "£3.50",
      "difficulty": "Beginner",
      "technique": "Copper foil",
      "delivery": "Instant download",
      "feeling": "Birds, flowers and small creatures, made to be made.",
      "traits": [
        "Beginner-friendly",
        "Nature-led",
        "Printable PDF"
      ],
      "cardUrl": "/to-make/ellien-bruce-e4",
      "patternCount": 47
    }
  ]
};
