// Auto-generated by tools/generate_directory_content.py from HA_To_Keep_Tier2_Tier3.xlsx.
// DO NOT EDIT MANUALLY — amend the workbook and regenerate.
window.HA_TO_KEEP_CONTENT = {
  "generatedFrom": "HA_To_Keep_Tier2_Tier3.xlsx",
  "images": {
    "logo": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/1f3bfb43-558e-4262-b2e2-d4e3b56bd77e/01-the-hope-anthology.jpg?content-type=image%2Fjpeg",
    "star": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/470da432-cdf9-45be-b3ba-2e9599ce5f4f/04-the-hope-anthology-botanical-star.png?content-type=image%2Fpng"
  },
  "navigation": [
    {
      "label": "To Keep",
      "url": "/to-keep"
    },
    {
      "label": "To Make",
      "url": "/to-make"
    },
    {
      "label": "The Story",
      "url": "/story"
    },
    {
      "label": "For Artists",
      "url": "/for-artists"
    },
    {
      "label": "Collective",
      "url": "/collective"
    }
  ],
  "page": {
    "eyebrow": "To Keep",
    "headingHtml": "Curated <em>Artists</em>",
    "intro": "A growing anthology of artists whose work carries meaning — pieces to lift you, anchor you, or simply stay with you. Every artist is here because their work holds a feeling worth keeping.",
    "stats": [
      {
        "value": 2,
        "label": "FOUNDING ARTISTS",
        "suffix": "of the first 50"
      },
      {
        "value": 31,
        "label": "WORKS"
      },
      {
        "value": 5,
        "label": "COLLECTIONS"
      }
    ]
  },
  "filters": {
    "medium": [
      "All",
      "Prints"
    ],
    "price": [
      "All",
      "Under £20",
      "£20–£50",
      "£50+"
    ]
  },
  "recruitment": {
    "eyebrow": "FOUNDING ARTISTS",
    "heading": "Your work could be here.",
    "body": "Free for the founding year. No commission ever. I just need some images, a bit of a description about you, and some links.",
    "linkLabel": "See how it works for artists →",
    "linkUrl": "/for-artists"
  },
  "collective": {
    "heading": "Something worth being part of.",
    "body": "New designs, behind-the-scenes making, and the occasional reminder that you’re doing better than you think. No noise. No pressure. Just the Anthology.",
    "buttonLabel": "Join the Collective",
    "buttonUrl": "/collective"
  },
  "footer": {
    "privacyUrl": "/privacy-policy",
    "accessibilityUrl": "/accessibility",
    "copyright": "© The Hope Anthology 2026"
  },
  "artists": [
    {
      "slug": "theresa-haskins",
      "active": true,
      "name": "Theresa Haskins",
      "buttonName": "Theresa",
      "artistNumber": 1,
      "badge": "Founding artist",
      "heroImage": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/cae2ef8f-9cf1-42c2-9bf1-15ae42926c41/theresa-haskins-curated-artist-hope-anthology-hero.jpg?content-type=image%2Fjpeg",
      "heroAlt": "Theresa Haskins — curated artist, The Hope Anthology",
      "medium": "Prints",
      "filterMedium": "Prints",
      "collections": [
        "The Meaning Alphabet",
        "Everyday Anchors",
        "Angel Numbers"
      ],
      "priceFrom": "£5.95",
      "feeling": "Symbols and anchors that carry everyday meaning.",
      "traits": [
        "Symbolic art",
        "Colour-led",
        "Life meaning"
      ],
      "cardUrl": "/to-keep/theresa-haskins"
    },
    {
      "slug": "theresa-german",
      "active": true,
      "name": "Theresa German",
      "buttonName": "Folk Prints",
      "artistNumber": 2,
      "badge": "Founding artist",
      "heroImage": "https://images.squarespace-cdn.com/content/6a258894c750534b28845855/73e64fed-7768-4d71-9357-f633df015130/theresa-german-curated-artist-hope-anthology-hero.jpg?content-type=image%2Fjpeg",
      "heroAlt": "Theresa German — curated artist, The Hope Anthology",
      "medium": "Prints",
      "filterMedium": "Prints",
      "collections": [
        "Woodland Folk",
        "Farm Folk"
      ],
      "priceFrom": "£4.75",
      "feeling": "Animal characters that hold a mirror to something in you.",
      "traits": [
        "Folk animals",
        "Character-led",
        "Nature-rooted"
      ],
      "cardUrl": "/to-keep/theresa-german"
    }
  ]
};
